apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongoDB

spec:
  template:
    metadata:
      name: mongodb-pod
      labels:
        app: mongoDB
    spec:
      containers:
        - name: mongodb-container
          image: mongo
          ports:
            - containerPort: 27017


  replicas: 4

  selector:
    matchLabels:
      app: mongoDB
