apiVersion: v1
kind: Service
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  ports:
    - port: 2368
  selector:
    app: ghost
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gt-pv-claim
  labels:
    app: ghost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  selector:
    matchLabels:
      app: ghost
      tier: frontend
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: ghost
        tier: frontend
    spec:
      containers:
      - image: ghost
        name: ghost
        ports:
        - containerPort: 2368
          name: wordpress
        volumeMounts:
        - name: ghost-persistent-storage
          mountPath: /var/lib/ghost/content
      volumes:
      - name: ghost-persistent-storage
        persistentVolumeClaim:
          claimName: gt-pv-claim
